version: "3.9"

services:
  etcd-manager:
    container_name: etcd-manager
    build: .
    environment:
      - NODE_ENV=production
      - ETCD_ENDPOINT=http://nemesis-etcd:2379
      - NEXT_PUBLIC_ETCD_ENDPOINT=nemesis-etcd:2379
    ports:
      - "9100:3000"
    networks:
      - nemesis-starter_nemesis

networks:
  nemesis-starter_nemesis:
    external: true
